name: Deploy

on: 
  push:
    branches:
    - main 

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: 'AKIAZQSXQGB4IPTPHIX4'
          aws-secret-access-key: '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'
          aws-region: ap-south-1
      - name: npm install
        env:
          CI: true
        run: |
          npm ci
      - name: deploy 
        run: |
          cd ./../.
          zip -r deploy.zip ./LAMBDA-ACTION/*
          aws lambda update-function-code --function-name=arn:aws:lambda:ap-south-1:654092284024:function:LAMBDA-ACTION --zip-file=fileb://deploy.zip
